### ISSUE TITLE
CoreBitcoin依赖安装需要权限

### ISSUE THREAD

**Issue by crystalztl** [RenrenBit/RRWallet#1]
Pre-downloading: `CoreBitcoin` from `https://git.coding.net/kufufu9/CoreBitcoin.git`, commit `a9a45125ecd2ba30a5f3bea5eaeeb14c7a120ba2`
Username for 'https://git.coding.net':

**Comment by kufufu9** [comment]
正在迁移到github

**Comment by kufufu9** [comment]
done
