### ISSUE TITLE
hd path of BSV is m/44'/145'/0'/0

### ISSUE THREAD

**Issue by soulmachine** [RenrenBit/RRWallet#17]
At this line of `BSVWallet.js` https://github.com/RenrenBit/RRWallet/blob/master/src/module/wallet/wallet/BSVWallet.js#L92:

```javascript
this.path = "m/44'/145'/0'/0/0";
```

The registered coin type for `BSV` should be  `m/44'/236'/0'/0`,  according to this [SLIP-0044 : Registered coin types for BIP-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md)

Why does RRWallet use a non-standard hd path?

**Comment by kufufu9** [comment]
`m/44'/145'/0'/0/0` is BCH hd path

In the early days, many BSV holders get BSV due to BCH hard fork. So we used the BCH hd path as BSV hd path

And we will support the specified hd path when import mnemonic.

**Comment by soulmachine** [comment]
I see, you make BCH and BSV use the same hd path for backward compatibility.
