### ISSUE TITLE
安装依赖失败 The authenticity of host 'gitlab.com (35.231.145.151)' can't be established.ser

### ISSUE THREAD

**Issue by SnoopPanda** [RenrenBit/RRWallet#2]
localhost:RRWallet sp$ npm ci
The authenticity of host 'gitlab.com (35.231.145.151)' can't be established.ser
ECDSA key fingerprint is SHA256:HbW3g8zUjNSksFbqTiUWPWg2Bq1x8xdGUrliXFzSnUw.
Are you sure you want to continue connecting (yes/no)? ⸨   ░░░░░░░░░░░░░░░⸩ ⠼ ex⸨                  ⸩ ⠹ extractTree: sill extract core-js@2.6.9 extracted to /Us
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@gitlab.com/mf-npm/buffer.git
npm ERR! 
npm ERR! Host key verification failed.
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sp/.npm/_logs/2020-02-13T08_59_11_180Z-debug.log

**Comment by wangke0809** [comment]
看着是和 #1 一样的问题，可以等迁移完毕

**Comment by kufufu9** [comment]
done
