### ISSUE TITLE
npm ci 出错

### ISSUE THREAD

**Issue by fuckgm** [RenrenBit/RRWallet#20]
npm ERR! Error while executing:
npm ERR! /usr/local/bin/git ls-remote -h -t ssh://git@github.com/kufufu9/buffer.git
npm ERR!
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: 无法读取远程仓库。
npm ERR!
npm ERR! 请确认您有正确的访问权限并且仓库存在。
npm ERR!
npm ERR! exited with error code: 128

**Comment by MRdoulestar** [comment]
Same question.

**Comment by kufufu9** [comment]
Add a SSH Key to your Github account.
