### ISSUE TITLE
安卓版编译后打开闪退

### ISSUE THREAD

**Issue by MRdoulestar** [RenrenBit/RRWallet#22]
安卓版的编译后在模拟器和真机上运行都会白屏闪退，在模拟器中看日志中如下：
![image](https://user-images.githubusercontent.com/18137763/92589411-156e7780-f2cd-11ea-8621-4f276db82a07.png)

**Comment by kufufu9** [comment]
`SignChecker`是包名检测的工具, 防止恶意修改包名. 若不需要可以移除相关代码

**Comment by MRdoulestar** [comment]
好的，谢谢！

> `SignChecker`是包名检测的工具, 防止恶意修改包名. 若不需要可以移除相关代码
